# Generated by Django 5.0.1 on 2025-08-16 18:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('visual_description', models.TextField(blank=True, null=True)),
                ('ui_elements', models.JSONField(blank=True, default=list)),
                ('dominant_colors', models.JSONField(blank=True, default=list)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['processing_status'], name='screenshots_process_f20f69_idx'), models.Index(fields=['uploaded_at'], name='screenshots_uploade_efff2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('text_confidence', models.FloatField(default=0.0)),
                ('visual_confidence', models.FloatField(default=0.0)),
                ('ui_confidence', models.FloatField(default=0.0)),
                ('color_confidence', models.FloatField(default=0.0)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('matched_text_snippets', models.JSONField(blank=True, default=list)),
                ('matched_visual_elements', models.JSONField(blank=True, default=list)),
                ('matched_ui_elements', models.JSONField(blank=True, default=list)),
                ('matched_colors', models.JSONField(blank=True, default=list)),
                ('search_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('screenshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='screenshots.screenshot')),
            ],
            options={
                'ordering': ['-overall_confidence', '-search_timestamp'],
                'indexes': [models.Index(fields=['query'], name='screenshots_query_7b0d14_idx'), models.Index(fields=['overall_confidence'], name='screenshots_overall_9637f4_idx'), models.Index(fields=['search_timestamp'], name='screenshots_search__bb523a_idx')],
            },
        ),
    ]
