# Generated by Django 5.0.1 on 2025-08-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='file_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='file_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='screenshot',
            index=models.Index(fields=['file_created_at'], name='screenshots_file_cr_f88087_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshot',
            index=models.Index(fields=['file_modified_at'], name='screenshots_file_mo_e2d763_idx'),
        ),
    ]
