# Generated by Django 5.0.1 on 2025-08-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0002_screenshot_file_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='color_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='error_states',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='visual_patterns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
