# Generated by Django 5.0.1 on 2025-08-16 19:45

from django.db import migrations, models
from django.contrib.auth.models import User
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0003_screenshot_color_context_screenshot_error_states_and_more'),
    ]

    operations = [
        # First, add the user field as nullable
        migrations.AddField(
            model_name='screenshot',
            name='user',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='screenshots',
                to='auth.user'
            ),
        ),
        # Create a default user if none exists
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                User.objects.get_or_create(
                    username='admin',
                    defaults={
                        'email': 'admin@example.com',
                        'is_staff': True,
                        'is_superuser': True
                    }
                )[0].set_password('admin123') or
                User.objects.get_or_create(
                    username='admin',
                    defaults={
                        'email': 'admin@example.com',
                        'is_staff': True,
                        'is_superuser': True
                    }
                )[0].save()
            ),
            reverse_code=migrations.RunPython.noop
        ),
        # Assign all existing screenshots to the first user
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                apps.get_model('screenshots', 'Screenshot').objects.filter(user__isnull=True).update(
                    user=User.objects.first()
                )
            ),
            reverse_code=migrations.RunPython.noop
        ),
        # Make the user field non-nullable
        migrations.AlterField(
            model_name='screenshot',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='screenshots',
                to='auth.user'
            ),
        ),
    ]
