# Generated by Django 5.0.1 on 2025-08-16 20:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0004_auto_20250816_1945'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=255, unique=True)),
                ('custom_batch_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('validating', 'Validating'), ('in_progress', 'In Progress'), ('finalizing', 'Finalizing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='validating', max_length=20)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('completed_requests', models.PositiveIntegerField(default=0)),
                ('failed_requests', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('batch_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='screenshots.batchjob')),
                ('screenshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_requests', to='screenshots.screenshot')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['batch_id'], name='screenshots_batch_i_dd0b09_idx'),
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['status'], name='screenshots_status_f61a84_idx'),
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['created_at'], name='screenshots_created_8c6d36_idx'),
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['user'], name='screenshots_user_id_17e9ad_idx'),
        ),
        migrations.AddIndex(
            model_name='batchrequest',
            index=models.Index(fields=['batch_job', 'status'], name='screenshots_batch_j_69b62d_idx'),
        ),
        migrations.AddIndex(
            model_name='batchrequest',
            index=models.Index(fields=['custom_id'], name='screenshots_custom__ccce4f_idx'),
        ),
        migrations.AddIndex(
            model_name='batchrequest',
            index=models.Index(fields=['screenshot'], name='screenshots_screens_7424cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batchrequest',
            unique_together={('batch_job', 'custom_id')},
        ),
    ]
